** USUARIO **
INSERT INTO T_FT_USUARIO VALUES(63557321010,'Fábio Coelho',TO_DATE('16/06/1985','DD/MM/YYYY'),'fabio.coelho@gmail.com',11919464992,'123456');
INSERT INTO T_FT_USUARIO VALUES(29207297051,'Jorge Pereira',TO_DATE('28/05/1982','DD/MM/YYYY'),'jorge.p@hotmail.com',61963033801,'abcdef');
INSERT INTO T_FT_USUARIO VALUES(89236616003,'Rita Alencar',TO_DATE('26/10/2003','DD/MM/YYYY'),'r_alencar@gmail.com',21954423780,'123abc');

** CONTA **
INSERT INTO T_FT_CONTA VALUES(SQ_FT_NR_CONTA.NEXTVAL,63557321010,'Conta Pessoal',1500);
INSERT INTO T_FT_CONTA VALUES(SQ_FT_NR_CONTA.NEXTVAL,63557321010,'Conta Trabalho',0);
INSERT INTO T_FT_CONTA VALUES(SQ_FT_NR_CONTA.NEXTVAL,29207297051,'Banco do Brasil',10000);
INSERT INTO T_FT_CONTA VALUES(SQ_FT_NR_CONTA.NEXTVAL,89236616003,'Bradesco',0);

** TIPO **
INSERT INTO T_FT_TIPO VALUES(SQ_FT_CD_TIPO.NEXTVAL,'ENTRADA');
INSERT INTO T_FT_TIPO VALUES(SQ_FT_CD_TIPO.NEXTVAL,'SAIDA');
INSERT INTO T_FT_TIPO VALUES(SQ_FT_CD_TIPO.NEXTVAL,'APLICAÇÃO');
INSERT INTO T_FT_TIPO VALUES(SQ_FT_CD_TIPO.NEXTVAL,'RESGATE');

** GRUPO CATEGORIA **
INSERT INTO T_FT_GRUPO_CATEGORIA VALUES(SQ_FT_CD_GRUPO.NEXTVAL,'Renda');
INSERT INTO T_FT_GRUPO_CATEGORIA VALUES(SQ_FT_CD_GRUPO.NEXTVAL,'Gastos Essenciais');
INSERT INTO T_FT_GRUPO_CATEGORIA VALUES(SQ_FT_CD_GRUPO.NEXTVAL,'Estilo de Vida');
INSERT INTO T_FT_GRUPO_CATEGORIA VALUES(SQ_FT_CD_GRUPO.NEXTVAL,'Investimentos');
INSERT INTO T_FT_GRUPO_CATEGORIA VALUES(SQ_FT_CD_GRUPO.NEXTVAL,'Empréstimos');
INSERT INTO T_FT_GRUPO_CATEGORIA VALUES(SQ_FT_CD_GRUPO.NEXTVAL,'Não classificado');

** CATEGORIA **
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,1,'Bônus');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,1,'Empréstimo');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,1,'Outras rendas');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,1,'Remuneração');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,1,'Rendimento');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,2,'Contas residenciais');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,2,'Educação');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,2,'Mercado');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,2,'Moradia');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,2,'Saúde');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,2,'Transporte');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'Bares / Restaurantes');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'Carro');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'Compras');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'Cuidados pessoais');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'Despesas do trabalho');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'Empregados doméstico');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'Família / Filhos');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'Lazer');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'Outros gastos');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'Presentes / Doações');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'Saques');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'Serviços');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'TV / Internet / Telefone');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'Taxas bancárias');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,3,'Viagem');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,4,'Aplicação');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,4,'Resgate');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,5,'Carnê');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,5,'Cheque especial');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,5,'Crediário');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,5,'Crédito consignado');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,5,'Juros');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,5,'Juros de cartão');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,5,'Outros empréstimos');
INSERT INTO T_FT_CATEGORIA VALUES(SQ_FT_CD_CATEGORIA.NEXTVAL,6,'Outros');

** INVESTIMENTO **
INSERT INTO T_FT_INVESTIMENTO VALUES(123456,SQ_FT_CD_INVESTIMENTO.NEXTVAL,'casa própria 2023',500,1000);
INSERT INTO T_FT_INVESTIMENTO VALUES(123457,SQ_FT_CD_INVESTIMENTO.NEXTVAL,'reserva emergencial',0,1000);

** TRANSACAO **
INSERT INTO T_FT_TRANSACAO VALUES(123456,SQ_FT_TRANSACAO.NEXTVAL,'salário janeiro',NULL,1,10000,TO_DATE('01/01/2001','DD/MM/YYYY'),4,'');
INSERT INTO T_FT_TRANSACAO VALUES(123456,SQ_FT_TRANSACAO.NEXTVAL,'compras do mês',NULL,2,458.99,TO_DATE('02/01/2001','DD/MM/YYYY'),8,'');
INSERT INTO T_FT_TRANSACAO VALUES(123456,SQ_FT_TRANSACAO.NEXTVAL,'aluguel',NULL,2,1000,TO_DATE('03/01/2001','DD/MM/YYYY'),9,'despesa');
INSERT INTO T_FT_TRANSACAO VALUES(123456,SQ_FT_TRANSACAO.NEXTVAL,'água',NULL,2,50,TO_DATE('04/01/2001','DD/MM/YYYY'),6,'despesa');
INSERT INTO T_FT_TRANSACAO VALUES(123456,SQ_FT_TRANSACAO.NEXTVAL,'luz',NULL,2,99.99,TO_DATE('05/01/2001','DD/MM/YYYY'),6,'despesa');
INSERT INTO T_FT_TRANSACAO VALUES(123456,SQ_FT_TRANSACAO.NEXTVAL,'aporte casa',10,3,5000,TO_DATE('06/01/2001','DD/MM/YYYY'),27,'casa 2023');
INSERT INTO T_FT_TRANSACAO VALUES(123456,SQ_FT_TRANSACAO.NEXTVAL,'aporte reserva',11,3,3950,TO_DATE('06/01/2001','DD/MM/YYYY'),27,'emergencial');
INSERT INTO T_FT_TRANSACAO VALUES(123458,SQ_FT_TRANSACAO.NEXTVAL,'salario janeiro',NULL,1,10000,TO_DATE('01/01/2001','DD/MM/YYYY'),4,'');
INSERT INTO T_FT_TRANSACAO VALUES(123458,SQ_FT_TRANSACAO.NEXTVAL,'tênis',NULL,2,100.99,TO_DATE('02/01/2001','DD/MM/YYYY'),14,'');
INSERT INTO T_FT_TRANSACAO VALUES(123458,SQ_FT_TRANSACAO.NEXTVAL,'blusa',NULL,2,250.99,TO_DATE('03/01/2001','DD/MM/YYYY'),14,'');
INSERT INTO T_FT_TRANSACAO VALUES(123458,SQ_FT_TRANSACAO.NEXTVAL,'camisa',NULL,2,35.50,TO_DATE('04/01/2001','DD/MM/YYYY'),14,'');
INSERT INTO T_FT_TRANSACAO VALUES(123458,SQ_FT_TRANSACAO.NEXTVAL,'açouge',NULL,2,100,TO_DATE('05/01/2001','DD/MM/YYYY'),8,'feijoada fds');

